#!/bin/bash
# Sets up the bootstrap configuration mismatch alert test.
#
# Usage: ./run.sh [env|endpoints|args]
#
#   env       (default) minio4 has MINIO_SITE_NAME=wrong-site
#             → ErrEnvMismatch (environment variable difference)
#
#   endpoints minio4 uses data{1...3} (3 drives) vs data{1...2} (2 drives)
#             → ErrEndpointCountMismatch (NEndpoints: 12 vs 8)
#
#   args      minio4 uses disk{1...2} paths vs data{1...2}
#             → ErrArgsMismatch (same drive count, different CmdLine string)
#
# In all cases nodes 1-3 agree and reach quorum. minio1 (FirstLocal) fires
# a config-mismatch alert for minio4. minio4 stays stuck in its bootstrap
# verification loop and never starts its S3 API — this is intentional.
#
# Run ./verify.sh [same-type] to confirm the alert reached Kafka and webhook.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MISMATCH_TYPE="${1:-env}"

echo "=== Bootstrap Config Mismatch Alert Test Setup ==="
echo ""

case "$MISMATCH_TYPE" in
  env|endpoints|args) ;;
  *)
    echo "Error: unknown mismatch type '$MISMATCH_TYPE'."
    echo "Usage: $0 [env|endpoints|args]"
    exit 1
    ;;
esac

echo "Mismatch type: $MISMATCH_TYPE"
case "$MISMATCH_TYPE" in
  env)       echo "  minio4 MINIO_SITE_NAME=wrong-site (nodes 1-3 use prod-cluster)" ;;
  endpoints) echo "  minio4 command uses data{1...3} — NEndpoints 12 vs 8" ;;
  args)      echo "  minio4 command uses disk{1...2} paths — CmdLine differs from data{1...2}" ;;
esac
echo ""

# --- Validate environment ---
for env_file in "$SCRIPT_DIR/../.env" "$SCRIPT_DIR/.env"; do
    if [ -f "$env_file" ]; then
        set -a; source "$env_file"; set +a
    fi
done

if [ -z "${MINIO_IMAGE:-}" ]; then
    echo "Error: MINIO_IMAGE is not set. Edit .env and set MINIO_IMAGE."
    exit 1
fi
if [ -z "${MINIO_LICENSE:-}" ]; then
    echo "Error: MINIO_LICENSE is not set. Edit .env and set MINIO_LICENSE."
    exit 1
fi

# Write a local .env so plain `docker compose down|logs|ps` works from
# this directory without sourcing the parent .env manually each time.
cat > "$SCRIPT_DIR/.env" <<EOF
MINIO_IMAGE=${MINIO_IMAGE}
MINIO_LICENSE=${MINIO_LICENSE}
MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
_MINIO_SUBNET_URL=${_MINIO_SUBNET_URL:-}
MINIO_CALLHOME_ENABLE=${MINIO_CALLHOME_ENABLE:-off}
EOF

# --- Write docker-compose override for minio4 ---
# The base docker-compose.yaml configures the env-var mismatch (MINIO_SITE_NAME).
# For endpoints/args types, write an override that changes minio4's command and
# fixes MINIO_SITE_NAME so only one mismatch type is active at a time.
# Docker Compose merges environment maps: the override's value wins on collision.
rm -f "$SCRIPT_DIR/docker-compose.override.yaml"

case "$MISMATCH_TYPE" in
  env)
    # No override needed — base compose already has MINIO_SITE_NAME=wrong-site.
    ;;

  endpoints)
    # minio4 uses 3 drives (data{1...3}) → NEndpoints 4×3=12 vs 4×2=8.
    # The extra /data3 tmpfs is included so MinIO can at least attempt startup.
    # minio4 never reaches quorum (all peers report wrong endpoint count) and
    # stays stuck in verifyServerSystemConfig.
    cat > "$SCRIPT_DIR/docker-compose.override.yaml" <<'OVERRIDE'
# Generated by run.sh endpoints
services:
  minio4:
    command: server http://minio{1...4}/data{1...3} --console-address ":9001"
    tmpfs:
      - /data1
      - /data2
      - /data3
    environment:
      MINIO_SITE_NAME: "prod-cluster"
OVERRIDE
    ;;

  args)
    # minio4 uses disk{1...2} drive paths — same drive count (4×2=8 endpoints)
    # but different CmdLine string → ErrArgsMismatch.
    # minio4 never reaches quorum (all peers report wrong CmdLine) and stays
    # stuck in verifyServerSystemConfig.
    #
    # tmpfs mounts for /disk1 and /disk2 are required: the MinIO image runs as
    # a non-root user and cannot create directories at the root of the
    # container filesystem. Without them, minio4 exits before starting its HTTP
    # server (so the port-open healthcheck never passes and minio1-3 stay in
    # 'created'). The override replaces the base tmpfs list (data1/data2), so
    # all required mounts must be listed here.
    cat > "$SCRIPT_DIR/docker-compose.override.yaml" <<'OVERRIDE'
# Generated by run.sh args
services:
  minio4:
    command: server http://minio{1...4}/disk{1...2} --console-address ":9001"
    tmpfs:
      - /disk1
      - /disk2
    environment:
      MINIO_SITE_NAME: "prod-cluster"
OVERRIDE
    ;;
esac

# --- Tear down any previous run ---
# The webhook is in-memory: its alert store carries over between runs if the
# container is not restarted. Running `docker compose up` after a previous
# test without first doing `down` would leave stale alerts in the webhook,
# causing verify.sh to find the wrong alert type.
echo "Tearing down any previous stack..."
cd "$SCRIPT_DIR"
docker compose down --remove-orphans

# --- Start services ---
echo "Using MinIO image: $MINIO_IMAGE"
echo "Starting services..."
docker compose up --build -d
echo ""

# --- Wait for health ---
echo "Waiting for services to be ready..."

echo -n "  Kafka: "
for i in $(seq 1 60); do
    if docker exec kafka-mismatch kafka-broker-api-versions --bootstrap-server localhost:29092 > /dev/null 2>&1; then
        echo "ready"
        break
    fi
    [ "$i" -eq 60 ] && { echo "TIMEOUT"; exit 1; }
    echo -n "."; sleep 2
done

echo -n "  Webhook: "
for i in $(seq 1 30); do
    if curl -sf http://localhost:9090/health > /dev/null 2>&1; then
        echo "ready"
        break
    fi
    [ "$i" -eq 30 ] && { echo "TIMEOUT"; exit 1; }
    echo -n "."; sleep 1
done

# Wait for the healthy majority (minio1-3) to complete bootstrap and start.
# minio4 will NOT become healthy — that is expected.
echo -n "  MinIO majority (minio1-3): "
for i in $(seq 1 90); do
    if curl -sf http://localhost:9010/minio/health/live > /dev/null 2>&1; then
        echo "ready"
        break
    fi
    [ "$i" -eq 90 ] && { echo "TIMEOUT"; exit 1; }
    echo -n "."; sleep 2
done

echo ""
echo "=== Services running ==="
echo ""
echo "  MinIO API:     http://localhost:9010  (minio1-3 only)"
echo "  MinIO Console: http://localhost:9011  (minioadmin / minioadmin)"
echo "  Webhook Stats: http://localhost:9090/stats"
echo "  Kafka:         localhost:9092 (topic: alert-events)"
echo ""
echo "NOTE: minio4 is intentionally stuck in bootstrap verification"
echo "      and will show as unhealthy. This is expected."
echo ""
echo "The config-mismatch alert ($MISMATCH_TYPE) was sent by minio1 during startup."
echo ""
echo "Next steps:"
echo "  ./verify.sh $MISMATCH_TYPE  # Check for the config-mismatch alert"
echo "  docker compose logs minio1-mismatch  # View minio1 logs (alert sender)"
echo "  docker compose logs minio4-mismatch  # View minio4 logs (stuck in loop)"
echo "  docker compose down                  # Stop and clean up"
